In [1]:
import os, pandas as pd, numpy as np, tensorflow as tf, keras, matplotlib.pyplot as plt

In [2]:
from random import random, seed, gauss

In [3]:
print(pd.__version__)
print(np.__version__)
print(tf.__version__)

1.0.5
1.18.1
2.2.0


In [4]:
mydates1 = pd.date_range(start='1/1/2018', end='1/12/2020', freq='MS')
n_mydates1 = len(mydates1)

In [5]:
df = pd.DataFrame()

In [6]:
seed = 1
rand1 = np.random.random((n_mydates1))
seed = 1
rand2 = np.random.random((n_mydates1))
print(rand1)
print(rand2)

[0.24238269 0.37502987 0.13759126 0.10782981 0.6974383  0.53533206
 0.06215357 0.72084242 0.83083935 0.39611145 0.92657206 0.74982345
 0.23953399 0.57862229 0.59934666 0.48536894 0.17873786 0.62101
 0.93465926 0.50401081 0.54131792 0.01255943 0.39353655 0.4909465
 0.63745723]
[0.758472   0.11954419 0.57782091 0.59931254 0.55241988 0.65263555
 0.05886852 0.98793513 0.25693762 0.35143332 0.6878048  0.70410894
 0.22130148 0.73887268 0.4335246  0.73463816 0.6457864  0.63517738
 0.20358215 0.50449645 0.47305174 0.63012993 0.92035299 0.15376516
 0.03220702]


In [7]:
r1minusr2 = rand1-rand2

In [8]:
r1minusr2

array([-5.16089308e-01,  2.55485684e-01, -4.40229652e-01, -4.91482725e-01,
        1.45018421e-01, -1.17303493e-01,  3.28504810e-03, -2.67092709e-01,
        5.73901726e-01,  4.46781376e-02,  2.38767253e-01,  4.57145066e-02,
        1.82325073e-02, -1.60250389e-01,  1.65822067e-01, -2.49269224e-01,
       -4.67048540e-01, -1.41673845e-02,  7.31077104e-01, -4.85639954e-04,
        6.82661879e-02, -6.17570504e-01, -5.26816442e-01,  3.37181345e-01,
        6.05250205e-01])

In [9]:
list_of_tuples = list(zip(mydates1, rand1, rand2, r1minusr2)) 

In [10]:
df = pd.DataFrame(list_of_tuples, columns = ['Date', 'Rand1', 'Rand2', 'C2-C3'])

In [11]:
df

Date     Rand1     Rand2     C2-C3
0  2018-01-01  0.242383  0.758472 -0.516089
1  2018-02-01  0.375030  0.119544  0.255486
2  2018-03-01  0.137591  0.577821 -0.440230
3  2018-04-01  0.107830  0.599313 -0.491483
4  2018-05-01  0.697438  0.552420  0.145018
5  2018-06-01  0.535332  0.652636 -0.117303
6  2018-07-01  0.062154  0.058869  0.003285
7  2018-08-01  0.720842  0.987935 -0.267093
8  2018-09-01  0.830839  0.256938  0.573902
9  2018-10-01  0.396111  0.351433  0.044678
10 2018-11-01  0.926572  0.687805  0.238767
11 2018-12-01  0.749823  0.704109  0.045715
12 2019-01-01  0.239534  0.221301  0.018233
13 2019-02-01  0.578622  0.738873 -0.160250
14 2019-03-01  0.599347  0.433525  0.165822
15 2019-04-01  0.485369  0.734638 -0.249269
16 2019-05-01  0.178738  0.645786 -0.467049
17 2019-06-01  0.621010  0.635177 -0.014167
18 2019-07-01  0.934659  0.203582  0.731077
19 2019-08-01  0.504011  0.504496 -0.000486
20 2019-09-01  0.541318  0.473052  0.068266
21 2019-10-01  0.012559  0.630130 -0.617571
22 2019-11-01  0.393537  0.920353 -0.526816
23 2019-12-01  0.490947  0.153765  0.337181
24 2020-01-01  0.637457  0.032207  0.605250

In [12]:
df2018 = pd.DataFrame(df.loc[df['Date'] < '2019-01-01'].values, columns = ['Date', 'Rand1', 'Rand2', 'C2-C3'])

In [13]:
df2018

Date      Rand1      Rand2       C2-C3
0  2018-01-01   0.242383   0.758472   -0.516089
1  2018-02-01    0.37503   0.119544    0.255486
2  2018-03-01   0.137591   0.577821    -0.44023
3  2018-04-01    0.10783   0.599313   -0.491483
4  2018-05-01   0.697438    0.55242    0.145018
5  2018-06-01   0.535332   0.652636   -0.117303
6  2018-07-01  0.0621536  0.0588685  0.00328505
7  2018-08-01   0.720842   0.987935   -0.267093
8  2018-09-01   0.830839   0.256938    0.573902
9  2018-10-01   0.396111   0.351433   0.0446781
10 2018-11-01   0.926572   0.687805    0.238767
11 2018-12-01   0.749823   0.704109   0.0457145

In [14]:
df2018_1 = pd.DataFrame(df.loc[pd.DatetimeIndex(df['Date']).year.values == 2018].values, columns = ['Date', 'Rand1', 'Rand2', 'C2-C3'])

In [15]:
df2018_1

Date      Rand1      Rand2       C2-C3
0  2018-01-01   0.242383   0.758472   -0.516089
1  2018-02-01    0.37503   0.119544    0.255486
2  2018-03-01   0.137591   0.577821    -0.44023
3  2018-04-01    0.10783   0.599313   -0.491483
4  2018-05-01   0.697438    0.55242    0.145018
5  2018-06-01   0.535332   0.652636   -0.117303
6  2018-07-01  0.0621536  0.0588685  0.00328505
7  2018-08-01   0.720842   0.987935   -0.267093
8  2018-09-01   0.830839   0.256938    0.573902
9  2018-10-01   0.396111   0.351433   0.0446781
10 2018-11-01   0.926572   0.687805    0.238767
11 2018-12-01   0.749823   0.704109   0.0457145

In [16]:
pd.DatetimeIndex(df['Date']).year.values

array([2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018,
       2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019,
       2019, 2019, 2020])

In [17]:
df2019_1 = pd.DataFrame(df.loc[pd.DatetimeIndex(df['Date']).year.values == 2019].values, columns = ['Date', 'Rand1', 'Rand2', 'C2-C3'])

In [18]:
df2020_1 = pd.DataFrame(df.loc[pd.DatetimeIndex(df['Date']).year.values == 2020].values, columns = ['Date', 'Rand1', 'Rand2', 'C2-C3'])

# Centigrade to Faranheit

In [19]:
# Generate n_total = 20 random numbers between 0 and 100
n_total = 32
temp_c = 100*np.random.random((n_total))
temp_f = 1.8*temp_c + 32

In [20]:
temp_c

array([49.71832297, 21.19346259, 27.28687339, 77.14472165, 68.67382179,
       35.51115948, 43.19030523, 49.97482085, 41.58640366, 45.76253666,
       75.85139902,  9.54798192, 39.09328974, 39.43717143, 56.39731689,
       47.70271297,  4.06666904, 11.22502694, 48.14349674, 84.97115253,
       42.77183911, 19.51311946, 26.87441975, 50.20424007, 68.69325894,
       81.19420075, 56.14555532, 59.01457441, 97.0796095 , 51.42747397,
       56.3186916 , 99.59655102])

In [21]:
temp_f

array([121.49298135,  70.14823266,  81.1163721 , 170.86049897,
       155.61287922,  95.92008706, 109.74254942, 121.95467753,
       106.85552658, 114.37256599, 168.53251823,  49.18636745,
       102.36792153, 102.98690858, 133.51517041, 117.86488335,
        39.32000428,  52.20504849, 118.65829413, 184.94807456,
       108.9893104 ,  67.12361502,  80.37395556, 122.36763213,
       155.6478661 , 178.14956134, 133.06199958, 138.22623394,
       206.7432971 , 124.56945315, 133.37364489, 211.27379184])

In [24]:
import tensorflow as tf
import keras
from keras import models
from keras import layers

In [31]:
#model = models.Sequential()
#model.add(layers.Dense(1, activation='sigmoid',input_shape=(1,)))
layer1 = tf.keras.layers.Dense(units=1, input_shape=[1])

In [32]:
from keras import optimizers

In [43]:
#model.compile(optimizer=optimizers.RMSprop(lr=0.01), loss='mse', metrics=['accuracy'])
model = tf.keras.Sequential([layer1])
model.compile(optimizer=optimizers.Adam(0.01), loss='mse')

In [44]:
model.fit(temp_c,temp_f,epochs=1000,verbose=False)

In [45]:
import array
x_test = np.array(array.array('d', [0., 100.]))
model.predict(x_test)

array([[ 31.999996],
       [212.      ]], dtype=float32)